#!/usr/bin/env python
from libpebble2.communication import PebbleConnection
from libpebble2.communication.transports.serial import SerialTransport
from libpebble2.communication.transports.qemu import QemuTransport
import time
import bluetooth
import logging
logging.basicConfig(level=logging.DEBUG)

def find_pebble():
    nearby_devices = bluetooth.discover_devices(duration=8, lookup_names=True, flush_cache=True, lookup_class=False)
    for addr, name in nearby_devices:
        logging.debug(f"{name} {addr}")
        if 'Pebble' in name:
            logging.info(f"Found Pebble {name} with address {addr}")
            return addr
    return None


def set_pebble_time(pebble_address):
    # Connect to the Pebble watch
    # pebble = PebbleConnection(SerialTransport(pebble_address))
    pebble = PebbleConnection(QemuTransport(pebble_address))
    logging.debug(f"Trying to connect with {pebble_address}...")
    pebble.connect()

    # Get the current timestamp
    current_timestamp = int(time.time())

    # Assuming there is a method to set time (please replace with the actual method)
    # The actual method to set time might look something like this, if it exists:
    pebble.system.set_time(current_timestamp)  

    # Close the connection
    pebble.disconnect()
    print("Time has been set on the Pebble.")

if __name__ == "__main__":
    pebble_address = find_pebble()
    if pebble_address:
        logging.info(f"Time set on Pebble with address {pebble_address}")
        set_pebble_time(pebble_address)
    else:
        logging.error("Pebble watch not found")


